# Params and config

This section includes some extra features related to __params__ and the __config__ file.

A full link of config info can be seen in the [nextflow docs](https://www.nextflow.io/docs/latest/config.html)

## Params

Workflow parameters can be set at the top of the primary `main.nf` file.

```{bash, eval=FALSE }
/*
 * Params
*/
params.dir = "."
params.outdir = "./results"
params.sample_name = "Sample_1"
params.fastqs = "/home/data/project123/raw_fastqs"
params.database = "/home/dbs/db123/db123.fastq"
params.conda_env = "/home/conda/envs/example_env"
params.rscript = "./rscripts/summary.rscript"
```

### Params to channel

When using params containing a file in the workflow it is common practice to convert them to a channel.

```{bash, eval=FALSE }
workflow {
  database_ch = file(params.database)
}
```

More info/examples in [Creating channels](#creating_channels)

## Config

You can contain a lot of info in a config file.

Your primary config file should be in the same directory as your primary `main.nf` file and should be named `nextflow.config`.
This will cause it to be used when you `nextflow run main.nf -resume`.

[Link to nextflow configuration doc](https://www.nextflow.io/docs/latest/config.html)

### Process directives

For [Process directives](#process_directives) you want to be the default of all processes in your workflow you can include them in your `nextflow.config`.

```{bash, eval=FALSE }
process {
  memory = 100.00GB
  cups = 8
  time = 30.d
}
```

### Params in config

You can include your `params` in your config file.

```{bash, eval=FALSE }
params {
  dir = "."
  outdir = "./results"
  sample_name = "Sample_1"
  fastqs = "/home/data/project123/raw_fastqs"
  database = "/home/dbs/db123/db123.fastq"
  conda_env = "/home/conda/envs/example_env"
  rscript = "./rscripts/summary.rscript"
}
```

Ensure you still use `params.` as a prefix in the various `.nf` files.

### Conda

Rather than needing to include `-use-conda` in your command line you can add the below to your `nextflow.config` to make your workflow use conda.

```{bash, eval=FALSE }
conda.enabled = true
```

### Container program

There are many different container programs. Below are what you can add to the `nextflow.config` to get the different ones to work.

This includes setting the path to the image (if using one) and enabling the specific container program.

```{bash, eval=FALSE }
/// Docker
process.container = 'nextflow/examples:latest'
docker.enabled = true
```

```{bash, eval=FALSE }
/// Singularity
process.container = '/path/to/singularity.img'
singularity.enabled = true
```

If using one of them ensure you specify the containers in the variosu processes.

[Link to container nextflow docs](https://www.nextflow.io/docs/latest/container.html)

### Config profiles


You can have multiple profiles in a `nextflow.config` file.

To use a profile you would run:

```{bash, eval=FALSE }
nextflow run main.nf -profile laptop
```

To make different profiles you could include the below in your `nextflow.config`.

```{bash, eval=FALSE }
profiles {
    laptop {
        process.executor = 'local'
        docker.enabled = true
    }
    hpc {
        process.executor = 'slurm'
        conda.enabled = true
        process.resourceLimits = [
            memory: 750.GB,
            cpus: 200,
            time: 30.d
        ]
    }
}
```


